TILE_SIZE = 64

WINDOW_CELLS_X = 15
WINDOW_CELLS_Y = 10

WINDOW_WIDTH = WINDOW_CELLS_X * TILE_SIZE
WINDOW_HEIGHT = WINDOW_CELLS_Y * TILE_SIZE

SNAKE_MAIN_TILE = "./assets/SnakeMainTile.png"
SNAKE_TILE = "./assets/SnakeTile.png"

FPS = 30